name: Test Jekyll Build

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Check for syntax errors
      run: bundle exec jekyll doctor
      
    - name: Build Jekyll site
      run: bundle exec jekyll build --strict_front_matter
      env:
        JEKYLL_ENV: development
        
    - name: Test HTML
      run: |
        gem install html-proofer
        htmlproofer ./_site --disable-external --check-html --check-img-http --check-opengraph
        
    - name: Test CSS
      run: |
        npm install -g csslint
        find ./_site -name "*.css" -exec csslint {} \;
        
    - name: Check links
      run: |
        gem install html-proofer
        htmlproofer ./_site --external_only --check-external-hash